---
title: "Cao_Xiping_AssignmentV"
author: "Xiping Cao"
date: "2/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Setting up a new GitHub repository
My project repository: https://github.com/cxp0330/AssignmentV.git

####Interacting with the API - the basics
```{r message=FALSE}
#load packages
rm(list = ls())

library(jsonlite)
library(httr)
library(rlist)
library(tidyverse)
library(naniar)

# set working directory:
#setwd("")
```

#### Interacting with the API - the basics
```{r message=FALSE}
# get API key
#APIkey <- "7elxdku9GGG5k8j0Xm8KWdANDgecHMV0"
source("Cao_Xiping_AssignmentV.R")

# get information from the API
Venues <- GET("https://app.ticketmaster.com/discovery/v2/venues?",
                    query =list(apikey = APIkey,
                                local = "*",
                                countryCode = "DE"))
Venues_content <- content(Venues)

# extract information from the resulting list
Venues_table <- tibble(name = character(20),
                       city = character(20),
                       postalCode =character(20),
                       address = character(20),
                       url = character(20),
                       longitude = character(20),
                       latitude = character(20))

for (i in 1:length(Venues_content[["_embedded"]][["venues"]])) {
  Venues_table$name[i] <- Venues_content[["_embedded"]][["venues"]][[i]][["name"]]
  Venues_table$city[i] <- Venues_content[["_embedded"]][["venues"]][[i]][["city"]][["name"]]
  Venues_table$postalCode[i] <- Venues_content[["_embedded"]][["venues"]][[i]][["postalCode"]]
  Venues_table$address[i] <- Venues_content[["_embedded"]][["venues"]][[i]][["address"]][["line1"]]
  Venues_table$url[i] <- Venues_content[["_embedded"]][["venues"]][[i]][["url"]]
  if(is.null(Venues_content[["_embedded"]][["venues"]][[i]][["location"]][["longitude"]])){
    next
  } else {
    Venues_table$longitude[i] <- Venues_content[["_embedded"]][["venues"]][[i]][["location"]][["longitude"]]
  }
    if(is.null(Venues_content[["_embedded"]][["venues"]][[i]][["location"]][["latitude"]])){
    next
  } else {
    Venues_table$latitude[i] <- Venues_content[["_embedded"]][["venues"]][[i]][["location"]][["latitude"]]
  }
  
}
```

#### Interacting with the API - advanced
```{r message=FALSE}
# total number of venues
n <- as.numeric(Venues_content[["page"]][["totalElements"]])
pages <- n %/% 20
remainder <- n %% 20

# extract information from the resulting list
Venues2_table <- tibble(name = character(n),
                       city = character(n),
                       postalCode =character(n),
                       address = character(n),
                       url = character(n),
                       longitude = character(n),
                       latitude = character(n))

for (j in 1:pages) {
  for (i in 1:20) {
    Venues2 <- GET("https://app.ticketmaster.com/discovery/v2/venues?",
                    query =list(apikey = APIkey,
                                local = "*",
                                countryCode = "DE",
                                page = "j"))
    Venues2_content <- content(Venues2)
        #name
        if(is.null(Venues2_content[["_embedded"]][["venues"]][[i]][["name"]])){
          next
        } else {
          Venues2_table$name[i+(j-1)*20] <- Venues2_content[["_embedded"]][["venues"]][[i]][["name"]]
        }
        #city
        if(is.null(Venues2_content[["_embedded"]][["venues"]][[i]][["city"]][["name"]])){
          next
        } else {
          Venues2_table$city[i+(j-1)*20] <- Venues2_content[["_embedded"]][["venues"]][[i]][["city"]][["name"]]
        }
        #postalCode
        if(is.null(Venues2_content[["_embedded"]][["venues"]][[i]][["postalCode"]])){
          next
        } else {
          Venues2_table$postalCode[i+(j-1)*20] <- Venues2_content[["_embedded"]][["venues"]][[i]][["postalCode"]]
        }
        #address
        if(is.null(Venues2_content[["_embedded"]][["venues"]][[i]][["address"]][["line1"]])){
          next
        } else {
          Venues2_table$address[i+(j-1)*20] <- Venues2_content[["_embedded"]][["venues"]][[i]][["address"]][["line1"]]
        }
        #url
        if(is.null(Venues2_content[["_embedded"]][["venues"]][[i]][["url"]] )){
          next
        } else {
         Venues2_table$url[i+(j-1)*20] <- Venues2_content[["_embedded"]][["venues"]][[i]][["url"]] 
        }
        #longitude
        if(is.null(Venues2_content[["_embedded"]][["venues"]][[i]][["location"]][["longitude"]])){
          next
        } else {
          Venues2_table$longitude[i+(j-1)*20] <- Venues2_content[["_embedded"]][["venues"]][[i]][["location"]][["longitude"]]
        }
        #latitude
        if(is.null(Venues2_content[["_embedded"]][["venues"]][[i]][["location"]][["latitude"]])){
          next
        } else {
          Venues2_table$latitude[i+(j-1)*20] <- Venues2_content[["_embedded"]][["venues"]][[i]][["location"]][["latitude"]]
        }
    }
}


```



```{r message=FALSE}
Venues3 <- GET("https://app.ticketmaster.com/discovery/v2/venues?",
                    query =list(apikey = APIkey,
                                local = "*",
                                countryCode = "DE"))
data <- fromJSON(rawToChar(Venues3$content))
```





















